####----------------------------------------------------------------------------
####----------------------------------------------------------------------------
      ## General Credentials
      - name: Generate Credentials
        id: generate_credentials
        run: |
          declare -a credentials=(
              aws_access_key_id~${AWS_ACCESS_KEY_ID}
              aws_secret_access_key~${AWS_SECRET_ACCESS_KEY}
            ) ;
          ## echo -e "\nDefault Credentials:\n${credentials[@]}" ;
          echo -e "\nInjecting Default User-Credentials into AWS-Credentials file! \n" ;
          for credential in ${credentials[@]}; do
            echo -e "Injecting Default User-Credential: ${credential%\~*} = ${credential#*\~} ..." ;
            sed -i -e "s|^\(${credential%\~*}\)\( =\)\(.*\)$|\1\2 ${credential#*\~}|g" ${AWS_SHARED_CREDENTIALS_FILE} ;
          done ;
          ## echo -e "\nDisplay Default User-Credentails (file):" ;
          ## cat ${AWS_SHARED_CREDENTIALS_FILE} ;
          echo -e "\nInitiating STS Assume Role request ..." ;
          declare -a session_token=($(
              aws --profile ${AWS_DEFAULT_PROFILE} \
                  --region ${AWS_DEFAULT_REGION} \
                  sts assume-role \
                  --role-arn arn:aws:iam::${AWS_DEFAULT_ACCOUNT}:role/${DEVOPS_ACCESS_ROLE} \
                  --role-session-name "${SESSION_TIMESTAMP}" \
                  --query 'Credentials.{aki:AccessKeyId,sak:SecretAccessKey,stk:SessionToken,sts:Expiration}' \
                  --output text
               )) ;
          echo -e "Fetched STS Assumed Role Values:" ;
          ## echo -e "Session Token:\n${session_token[@]}" ;
          declare -a session_items=(AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_TOKEN_EXPIRES) ;
          ## echo -e "\nConstructed Session Items [array]:\n${session_items[@]}\n" ;
          counter=0; for xkey in "${session_token[@]}"; do
            ## eval "export ${session_items[$((counter++))]}=${xkey}" ;
            ## echo -e "Exporting Session Variables: ${session_items[${counter}]} = ${xkey}" ;
            eval "echo '::set-env name=${session_items[$((counter++))]}::${xkey}'" ;
          done ;
        continue-on-error: false
      - name: Check On Failures
        if: steps.generate_credentials.outputs.status == 'failure'
        run: echo "${{ steps.generate_credentials.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## Inspect Credentials
      - name: Inspecting User Credentials
        id: inspect_credentials
        run: |
          echo ::add-mask::${DEVOPS_ACCOUNT_ID} ;
          echo -e "Obtaining STS Caller Identity (First-Time)" ;
          aws --profile ${AWS_DEFAULT_PROFILE} \
              --region ${AWS_DEFAULT_REGION} \
              sts get-caller-identity ;
        continue-on-error: false
      - name: Check On Failures
        if: steps.inspect_credentials.outputs.status == 'failure'
        run: echo "${{ steps.inspect_credentials.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## DevOps Assume-Role
      - name: DevOps Assume-Role
        id: devops_assumerole
        run: |
          declare -a credentials=(
              aws_access_key_id~${AWS_ACCESS_KEY_ID}
              aws_secret_access_key~${AWS_SECRET_ACCESS_KEY}
              aws_session_token~${AWS_SESSION_TOKEN}
              x_principal_arn~arn:aws:iam::${AWS_DEFAULT_ACCOUNT}:user/${DEVOPS_ACCOUNT_NAME}
              x_security_token_expires~${AWS_TOKEN_EXPIRES}
            ) ;
          ## echo -e "Displaying Latest Credentials:\n${credentials[@]}\n" ;
          for credential in ${credentials[@]}; do
            ## echo -e "Injecting Latest Credential:\n${credential%\~*} = ${credential#*\~} ..." ;
            sed -i -e "s|^\(${credential%\~*}\)\( =\)\(.*\)$|\1\2 ${credential#*\~}|g" ${AWS_SHARED_CREDENTIALS_FILE} ;
          done ;
        continue-on-error: false
      - name: Check On Failures
        if: steps.devops_assumerole.outputs.status == 'failure'
        run: echo "${{ steps.devops_assumerole.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## Confirm Credentials
      - name: Confirming User Credentials
        id: confirm_credentials
        run: |
          echo -e "Obtaining Caller Identity (Second-Time)" ;
          aws --profile ${AWS_DEFAULT_PROFILE} \
              --region ${AWS_DEFAULT_REGION} \
              sts get-caller-identity ;
        continue-on-error: false
      - name: Check On Failures
        if: steps.confirm_credentials.outputs.status == 'failure'
        run: echo "${{ steps.confirm_credentials.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## Display Environment
      - name: Display Environment
        id: display_environment
        if: env.display_environment == 'true'
        run: |
          echo -e "Displaying Enviroment Settings ..." ;
          echo -e "Terraform Workspace: ${TARGET_WORKSPACE} " ;
          echo -e "Terraform Cloud-Region: ${AWS_DEFAULT_REGION} \n" ;
          echo -e "AWS Target Account: ${AWS_DEFAULT_ACCOUNT}" ;
          echo -e "AWS Access Key-ID: ${AWS_ACCESS_KEY_ID}" ;
          echo -e "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY}" ;
          echo -e "AWS Session Token: ${AWS_SESSION_TOKEN}" ;
        continue-on-error: true
      - name: Check On Failures
        if: steps.display_environment.outputs.status == 'failure'
        run: echo "${{ steps.display_environment.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## Validating AWS CLI
      - name: Validating AWS CLI
        id: validate_awscli
        run: |
          ## echo -e "Listing Current Credentials Configurations ..." ;
          ## cat ${AWS_SHARED_CREDENTIALS_FILE} ;
          aws configure list ;
          echo ::add-mask::${DEVOPS_ACCOUNT_ID} ;
          echo -e "\nListing IAM Users (Assumed-Role):" ;
          aws --profile ${AWS_DEFAULT_PROFILE} \
              --region ${AWS_DEFAULT_REGION} \
              iam list-users \
              --query 'Users[?UserName==`'${DEVOPS_ACCOUNT_NAME}'`]' ;
        continue-on-error: false
      - name: Check On Failures
        if: steps.validate_awscli.outputs.status == 'failure'
        run: echo "${{ steps.validate_awscli.outputs.status }}" ;
####----------------------------------------------------------------------------
